---
title: "strike-impact-project"
author: "Kehan Liu"
date: "27/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(psych)
library(naniar)

options(scipen = 999)

likert_levels <- c(
  "Strongly disagree", 
  "Disagree", 
  "Neither agree nor disagree", 
  "Agree", 
  "Strongly agree") 

degree_levels <- c(
  "Undergraduate",
  "Postgraduate"
)

d_strike_impact <- read_csv(
  '../data/Survey.csv',
  col_types = cols(
    col_character(),
    col_factor(ordered = FALSE, levels = degree_levels),
    col_number(),
    col_number(),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_character()
  ))

d_strike_impact <- d_strike_impact %>%
  mutate(
    across(
      .cols = c(starts_with('learn'), 'forget_knowledge', 'admin_impact'),
      .fns = as.numeric,
      .names = '{.col}_coded'
    )
  )

d_strike_impact <- d_strike_impact %>%
  mutate(
    impact_mod_prop = round(impact_mod/total_mod, digits = 2)
  )

keys_list <- list(
  strike_attitude = c(
    'learn_interest_coded',
    'learn_pressure_coded',
    'forget_knowledge_coded',
    'admin_impact_coded'
  )
)

strike_impact_scores <- scoreItems(
  keys = keys_list,
  items = d_strike_impact,
  totals = FALSE,
  missing = TRUE, 
  impute = 'none'
)

d_strike_impact <- cbind(d_strike_impact, strike_impact_scores$scores)

```


```{r}
impact_likert_summary <- d_strike_impact %>%
  select(ends_with('_coded')) %>%
  lapply(
    median, na.rm = TRUE
  )

d_impact_likert_summary <- tibble(
  Item = impact_likert_summary %>% names,
  Median = impact_likert_summary %>% unlist
)

d_impact_likert_summary

d_impact_likert_summary %>%
  ggplot(
    aes(x = Item, y = Median)
  ) +
  geom_point()
```


```{r}
d_strike_impact <- d_strike_impact %>%
  mutate(
    Negative = overall_performance == 'Negative'
  )

d_negative <- d_strike_impact %>%
  group_by(faculty) %>%
  summarise(
    n = n(),
    n_neg = sum(Negative, na.rm = TRUE)
  ) %>%
  mutate(
    Percentage = round(n_neg / n * 100)
  ) %>%
  tibble()

d_negative

fisher.test(
  d_strike_impact$faculty,
  d_strike_impact$Negative
)

```

```{r}
d_strike_impact %>%
  ggplot(aes(x = impact_mod_prop, y = strike_attitude, color = deg_lev)) +
  geom_jitter(alpha = 0.7) +
  geom_smooth(method = lm, se = FALSE, fullrange = TRUE, aes(color = deg_lev))

```


```{r}
d_strike_impact <- d_strike_impact %>%
  mutate(
    Posgrad = deg_lev == 'Postgraduate'
  ) %>%
  replace_with_na(replace = list(impact_mod_prop = 5))

d_strike_impact %>%
  mutate(Posgrad = Posgrad %>% as.numeric) %>%
  lm(strike_attitude ~ impact_mod_prop + Posgrad, data = ., na.action = na.exclude) %>%
  summary

```






